#!/usr/bin/env python
"""Write the TikZ/pgfplots source of every data figure from the result files.

Each figure reads its numbers from the committed files in experiments/ntc, so a
figure cannot drift from the data it plots. The thirteen data figures are
written to figures/src (or --out); the eight diagrams in figures/src are
authored by hand. figures/build.sh renders all of them to PDF.

    python scripts/make_figures.py [--out figures/src]
"""
from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
NTC = ROOT / "experiments" / "ntc"
WORDS = ("zero one two three four five six seven eight nine ten eleven twelve thirteen "
         "fourteen fifteen sixteen seventeen eighteen nineteen").split()
TENS = "_ _ twenty thirty forty fifty sixty seventy eighty ninety".split()


# ----------------------------------------------------------------- helpers
def read(name: str) -> str:
    return (NTC / name).read_text()


def rows(text, start=None):
    """Markdown table rows as lists of cells, from `start` to the next heading."""
    if start:
        i = text.index(start)
        j = text.find("\n## ", i + len(start))
        text = text[i:j if j > 0 else len(text)]
    return [[c.strip() for c in ln.strip().strip("|").split("|")]
            for ln in text.splitlines() if ln.startswith("|") and "---" not in ln]


def num(s):
    m = re.search(r"[-+]?\d*\.?\d+", str(s))
    return float(m.group()) if m else None


def words(n: int) -> str:
    if n < 20:
        return WORDS[n]
    t, u = divmod(n, 10)
    return TENS[t] + ("" if u == 0 else "-" + WORDS[u])


def thousands(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def header(title: str, source: str) -> str:
    return f"% {title}\n% (generated by scripts/make_figures.py from experiments/ntc/{source})\n"


def slo_table():
    text = read("SLO_ATTAINMENT.md")
    hdr = next(r for r in rows(text) if r[0] == "setting")
    body = {r[0]: r for r in rows(text) if r[0] != "setting"}

    def deficit(setting, method):
        return float(body[setting][hdr.index(method)].split("(")[0].replace("+", ""))

    att = {}
    for ln in text.splitlines():
        m = re.match(r"- `([^`]+)`.*?within 1.0pt:\s*(\d+)%.*?within 2.5pt:\s*(\d+)%"
                     r".*?within 5.0pt:\s*(\d+)%", ln)
        if m:
            att[m.group(1)] = tuple(int(m.group(k)) for k in (2, 3, 4))
    return deficit, att


# ----------------------------------------------------------------- figures
def fig_heatmap():
    deficit, _ = slo_table()
    SET = [("GSM8K-4B", "gsm8k_Qwen3-4B"), ("GSM8K-8B", "gsm8k_Qwen3-8B"),
           ("MATH-1.7B", "math500_Qwen3-1.7B"), ("MATH-4B", "math500_Qwen3-4B"),
           ("MATH-8B", "math500_Qwen3-8B"), ("MMLU-4B", "mmlupro_Qwen3-4B"),
           ("MMLU-8B", "mmlupro_Qwen3-8B"), ("GPQA-4B", "gpqash_Qwen3-4B"),
           ("GPQA-8B", "gpqash_Qwen3-8B"), ("AIME-24", "aime24_avg8"),
           ("AIME-25", "aime25_avg8")]
    SIG = [("agreement", "AGREE"), ("confidence", "DEER"), ("entropy", "EAT"),
           ("momentum", "MUR-mom"), ("smoothed", "NTC-conf"), ("bandit", "REFRAIN-SWUCB"),
           ("fusion", "NTC-v2")]
    cells = []
    for i, (_, skey) in enumerate(SET):
        for j, (_, mkey) in enumerate(SIG):
            v = deficit(skey, mkey)
            if v < 0:
                shade = min(100, round(100 * abs(v) / 24.0) + 6)
                fill = f"lossred!{shade}"
            else:
                shade = min(100, round(100 * v / 8.5) + 6)
                fill = f"gainteal!{shade}"
            txt = f"{v:+.1f}" if abs(v) >= 0.05 else "0.0"
            dark = "white" if shade > 55 else "black"
            cells.append(f"\\node[hcell,fill={fill},text={dark}] at ({j*1.56+1.86},{-i*0.52}) "
                         f"{{{txt}}};")
    head = "\n".join(f"\\node[hhead] at ({j*1.56+1.86},0.52) {{{m}}};"
                     for j, (m, _) in enumerate(SIG))
    side = "\n".join(f"\\node[hside] at (1.02,{-i*0.52}) {{{s}}};"
                     for i, (s, _) in enumerate(SET))
    return (header("Accuracy change of every signal in every setting", "SLO_ATTAINMENT.md") +
            "\\begin{tikzpicture}[\n"
            "  hcell/.style={minimum width=1.52cm,minimum height=0.5cm,inner sep=0pt,\n"
            "                font=\\scriptsize,draw=white,line width=0.6pt},\n"
            "  hhead/.style={font=\\scriptsize\\bfseries,text=brunelnavy},\n"
            "  hside/.style={font=\\scriptsize,anchor=east,text=textgrey}]\n"
            + head + "\n" + side + "\n" + "\n".join(cells) + "\n"
            "\\node[font=\\scriptsize\\itshape,text=textgrey,anchor=west] at (0.1,-6.0)\n"
            "  {accuracy change against full generation, in points; red is a loss};\n"
            "\\end{tikzpicture}\n")


def fig_collapse():
    deficit, _ = slo_table()
    SET = [("GSM8K-8B", "gsm8k_Qwen3-8B"), ("MATH-4B", "math500_Qwen3-4B"),
           ("MMLU-Pro-4B", "mmlupro_Qwen3-4B"), ("GPQA-D-8B", "gpqash_Qwen3-8B"),
           ("AIME-24-4B", "aime24_avg8"), ("AIME-25-4B", "aime25_avg8")]
    ag = [(lab, deficit(key, "AGREE")) for lab, key in SET]
    fu = [(lab, deficit(key, "NTC-v2")) for lab, key in SET]

    def coords(pts):
        items = [f"({lab},{v:.1f})" for lab, v in pts]
        return "  {" + " ".join(items[:3]) + "\n   " + " ".join(items[3:]) + "};\n"

    hi = max(ag, key=lambda p: p[1])
    lo = min(ag, key=lambda p: p[1])
    spread = hi[1] - lo[1]
    whole = math.ceil(spread)
    phrase = (f"almost {words(whole)}" if whole - spread < 0.5 else f"over {words(int(spread))}")
    return (header("Collapse of the strongest fixed signal", "SLO_ATTAINMENT.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=6.2cm, width=13.0cm,\n"
            "  ybar, bar width=11pt,\n"
            "  ymin=-29, ymax=13,\n"
            "  ylabel={$\\Delta$ accuracy vs full thinking (points)},\n"
            "  symbolic x coords={" + ",".join(lab for lab, _ in SET) + "},\n"
            "  xtick=data, x tick label style={font=\\scriptsize},\n"
            "  ymajorgrids=true, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.5,-0.19)},anchor=north,legend columns=2,column sep=1.1em},\n"
            "  enlarge x limits=0.10]\n"
            "\\addplot[draw=brunelnavy,fill=rulegrey] coordinates\n" + coords(ag) +
            "\\addlegendentry{answer agreement (strongest fixed signal)}\n"
            "\\addplot[draw=brunelnavy,fill=accent] coordinates\n" + coords(fu) +
            "\\addlegendentry{NTC fusion tier (proposed)}\n\n"
            "\\node[font=\\scriptsize,color=brunelnavy,anchor=south]\n"
            f"  at (axis cs:{hi[0]},{hi[1] + 0.7:.1f}) {{${hi[1]:+.1f}$}};\n"
            "\\node[font=\\scriptsize,color=brunelnavy,anchor=north east]\n"
            f"  at (axis cs:{lo[0]},{lo[1] - 0.9:.1f}) {{${lo[1]:+.1f}$}};\n"
            f"\\draw[rulegrey,thin] (axis cs:{SET[0][0]},0) -- (axis cs:{SET[-1][0]},0);\n"
            "\\node[font=\\scriptsize\\itshape,color=textgrey,anchor=west,align=left]\n"
            f"  at (axis cs:{SET[0][0]},-19.5) {{a spread of {phrase}\\\\accuracy points "
            "from a single rule};\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_slo():
    _, att = slo_table()
    ORDER = [("NTC-Fuse", "NTC-v2"), ("NTC-Select", "NTC-full(e=0.01)"),
             ("smoothed", "NTC-conf"), ("entropy", "EAT"), ("confidence", "DEER"),
             ("bandit", "REFRAIN-SWUCB"), ("agreement", "AGREE"), ("momentum", "MUR-mom")]
    ycoords = ["momentum", "agreement", "bandit", "confidence", "entropy", "smoothed",
               "NTC-Select", "NTC-Fuse"]
    plots = []
    for k, (fill, legend) in enumerate([("accent", "within 1 pt"), ("midnavy", "within 2.5 pt"),
                                         ("rulegrey", "within 5 pt")]):
        pts = [f"({att[key][k]},{lab})" for lab, key in ORDER]
        plots.append(f"\\addplot[draw=brunelnavy,fill={fill}] coordinates\n"
                     f"  {{{' '.join(pts[:4])}\n   {' '.join(pts[4:])}}};\n"
                     f"\\addlegendentry{{{legend}}}\n")
    return (header("Share of settings holding each accuracy tolerance", "SLO_ATTAINMENT.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=6.4cm, width=11.4cm,\n"
            "  xbar, bar width=5.2pt,\n"
            "  xmin=0, xmax=118, xlabel={settings holding the accuracy budget (\\%)},\n"
            "  symbolic y coords={" + ",".join(ycoords[:6]) + ",\n"
            "                     " + ",".join(ycoords[6:]) + "},\n"
            "  ytick=data, y tick label style={font=\\footnotesize},\n"
            "  xmajorgrids=true, axis y line*=left, axis x line*=bottom,\n"
            "  legend style={at={(0.5,-0.28)},anchor=north,legend columns=3,column sep=0.9em},\n"
            "  enlarge y limits=0.09]\n" + "".join(plots) +
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_mechanism():
    text = read("PROP2_VALIDATION.md")
    hdr = next(r for r in rows(text) if r[0].startswith("benchmark"))
    data = [r for r in rows(text) if "/" in r[0] and r[0] != hdr[0]]
    ir, il = hdr.index("rho_w"), hdr.index("lost-correct risk")
    cls = {"gpqa_diamond": "four", "mmlu_pro": "ten"}
    pts = [(float(r[ir]), float(r[il]), cls.get(r[0].split("/")[0], "open"), r[0]) for r in data]
    groups = []
    for c in ("open", "ten", "four"):
        g = sorted((p for p in pts if p[2] == c), key=lambda p: (p[0], p[1]))
        toks = [f"({x:.3f},{y:.3f})[{c}]" for x, y, _, _ in g]
        groups += [toks[i:i + 4] for i in range(0, len(toks), 4)]
    lines = ["  " + " ".join(t.ljust(19) for t in g).rstrip() for g in groups]
    slope, icpt = np.polyfit([p[0] for p in pts], [p[1] for p in pts], 1)
    rho_s = float(re.search(r"Spearman\(P_spur, lost-correct risk\) = ([-+]\d\.\d+)", text).group(1))
    at = {p[3]: p for p in pts}
    a24, g8, gsm = at["aime24/Qwen3-4B"], at["gpqa_diamond/Qwen3-8B"], at["gsm8k/Qwen3-8B"]
    return (header("Error stickiness against lost-correct risk", "PROP2_VALIDATION.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=6.0cm, width=12.4cm,\n"
            "  xlabel={error stickiness $\\rho_w$}, ylabel={lost-correct risk},\n"
            "  xmin=0.08, xmax=0.83, ymin=0, ymax=0.50,\n"
            "  grid=both, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.02,0.97)},anchor=north west},\n"
            "  scatter/classes={\n"
            "    open={draw=brunelnavy,fill=midnavy,mark=*,mark size=2.1pt},\n"
            "    ten={draw=brunelnavy,fill=accent,mark=square*,mark size=2.1pt},\n"
            "    four={draw=brunelnavy,fill=white,mark=triangle*,mark size=2.6pt}}]\n"
            "\\addplot[scatter,only marks,scatter src=explicit symbolic]\n"
            " coordinates {\n" + "\n".join(lines) + "};\n"
            "\\legend{open-ended,$|\\mathcal{A}|=10$,$|\\mathcal{A}|=4$}\n"
            "\\addplot[draw=brunelnavy,dashed,line width=0.8pt,domain=0.10:0.80,forget plot]\n"
            f"  {{{icpt:.4f} + {slope:.4f}*x}};\n"
            "\\node[font=\\scriptsize,color=brunelnavy,anchor=south east] at (axis cs:0.80,0.045)\n"
            f"  {{Spearman $\\rho = {rho_s:+.2f}$ \\ ($n={len(pts)}$)}};\n"
            f"\\node[font=\\scriptsize,color=textgrey,anchor=east] at (axis cs:{a24[0] - 0.013:.3f},"
            f"{a24[1]:.3f}) {{AIME-24}};\n"
            f"\\node[font=\\scriptsize,color=textgrey,anchor=east] at (axis cs:{g8[0] - 0.012:.3f},"
            f"{g8[1]:.3f}) {{GPQA-8B}};\n"
            f"\\node[font=\\scriptsize,color=textgrey,anchor=west] at (axis cs:{gsm[0] + 0.021:.3f},"
            f"{gsm[1] + 0.032:.3f}) {{GSM8K}};\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_tradeoff():
    text = read("PRIMARY_STATS.md")
    op = {r[0]: num(r[1]) for r in rows(text, "## OPERATIONAL-REGION") if r[0] != "method"}
    reg = {r[0]: num(r[1]) for r in rows(text, "## Minimax regret") if r[0] != "method"}
    fu, se = "NTC-v2 (fusion)", "NTC-full (selection)"
    fixed = [("Answer agreement", "agreement", "south"), ("Entropy (EAT)", "entropy (EAT)", "west"),
             ("Smoothed confidence", "smoothed", "west"), ("Confidence (DEER-λ)", "confidence", "west")]
    xs = list(op.values())
    xmin, xmax = min(xs) - 0.016, max(xs) + 0.022
    ag = "Answer agreement"
    label = []
    for key, lab, anchor in fixed:
        if anchor == "south":
            label.append(f"\\node[font=\\scriptsize,color=textgrey,anchor=south] at "
                         f"(axis cs:{op[key]:.3f},{reg[key] + 0.008:.3f}) {{{lab}}};")
        else:
            label.append(f"\\node[font=\\scriptsize,color=textgrey,anchor=west] at "
                         f"(axis cs:{op[key] + 0.0025:.4f},{reg[key]:.3f}) {{{lab}}};")
    label.insert(1, f"\\node[font=\\scriptsize,color=textgrey,anchor=west] at "
                    f"(axis cs:{op[se] + 0.0025:.4f},{reg[se]:.3f}) {{selection}};")
    ratio = reg[ag] / reg[fu]
    return (header("Mean performance against worst-case risk", "PRIMARY_STATS.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=6.1cm, width=12.4cm,\n"
            "  xlabel={op-AUCC (mean performance; higher is better)},\n"
            "  ylabel={minimax regret (worst case; lower is better)},\n"
            f"  xmin={xmin:.3f}, xmax={xmax:.3f}, ymin=-0.02, ymax=0.30,\n"
            "  grid=both, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.5,-0.21)},anchor=north,legend columns=3,column sep=0.9em}]\n"
            "\\addplot[only marks,mark=*,mark size=2.7pt,draw=brunelnavy,fill=accent]\n"
            f"  coordinates {{({op[fu]:.3f},{reg[fu]:.3f})}};\n"
            "\\addlegendentry{NTC fusion tier}\n"
            "\\addplot[only marks,mark=square*,mark size=2.4pt,draw=brunelnavy,fill=midnavy]\n"
            f"  coordinates {{({op[se]:.3f},{reg[se]:.3f})}};\n"
            "\\addlegendentry{NTC selection tier}\n"
            "\\addplot[only marks,mark=triangle*,mark size=2.9pt,draw=brunelnavy,fill=rulegrey]\n"
            "  coordinates {" + " ".join(f"({op[k]:.3f},{reg[k]:.3f})" for k, _, _ in fixed) + "};\n"
            "\\addlegendentry{fixed signals}\n"
            f"\\node[font=\\scriptsize,anchor=east]  at (axis cs:{op[fu] - 0.0025:.4f},{reg[fu]:.3f}) "
            "{fusion};\n" + "\n".join(label) + "\n"
            f"\\draw[accent,dashed,line width=0.7pt] (axis cs:{op[ag]:.3f},{reg[ag]:.3f}) -- "
            f"(axis cs:{op[fu]:.3f},{reg[fu]:.3f});\n"
            "\\node[font=\\scriptsize\\itshape,color=accent,anchor=west,align=left]\n"
            f"  at (axis cs:{op[fu] - 0.050:.3f},0.050) {{near-identical mean,\\\\"
            f"${ratio:.1f}\\times$ lower worst case}};\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_shift():
    r = {row[0].split(" (")[0]: row for row in rows(read("SHIFT_CERTIFICATE.md"), "## eps = 0.05")}
    keys = ["in-domain", "transferred", "domain-robust"]

    def fmt(v):
        return "0" if v == 0 else f"{v:.1f}"
    within = " ".join(f"({k},{num(r[k][4]):.0f})" for k in keys)
    cut = " ".join(f"({k},{num(r[k][5]):.1f})" for k in keys)
    worst = " ".join(f"({k},{fmt(num(r[k][2]))})" for k in keys)
    return (header("The certificate under domain shift", "SHIFT_CERTIFICATE.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=5.9cm, width=12.6cm,\n"
            "  ybar, bar width=13pt,\n"
            "  ymin=-60, ymax=118,\n"
            "  ylabel={per cent \\ / \\ accuracy points},\n"
            "  symbolic x coords={in-domain,transferred,domain-robust},\n"
            "  xtick=data, x tick label style={font=\\footnotesize},\n"
            "  ymajorgrids=true, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.5,-0.17)},anchor=north,legend columns=3,column sep=0.9em},\n"
            "  enlarge x limits=0.30]\n"
            f"\\addplot[draw=brunelnavy,fill=accent] coordinates\n  {{{within}}};\n"
            "\\addlegendentry{within $\\varepsilon=0.05$ (\\%)}\n"
            f"\\addplot[draw=brunelnavy,fill=rulegrey] coordinates\n  {{{cut}}};\n"
            "\\addlegendentry{mean token cut (\\%)}\n"
            f"\\addplot[draw=brunelnavy,fill=midnavy] coordinates\n  {{{worst}}};\n"
            "\\addlegendentry{worst-cell deficit (pts)}\n"
            "\\draw[rulegrey,thin] (axis cs:in-domain,0) -- (axis cs:domain-robust,0);\n"
            "\\node[font=\\scriptsize\\itshape,color=brunelnavy,anchor=west,align=left]\n"
            "  at (axis cs:in-domain,-40) {guarantee void under transfer};\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_corpus():
    text = read("CORPUS_TRACKS.md")
    LAB = [("GSM8K", "GSM8K"), ("MATH-500", "MATH-500"), ("GPQA-D", "GPQA-Diamond"),
           ("MMLU-Pro", "MMLU-Pro"), ("AIME-24", "AIME-2024"), ("AIME-25", "AIME-2025")]
    tracks = []
    for sec in ("## primary", "## head-to-head", "## density"):
        t = {r[0]: int(r[6]) for r in rows(text, sec) if r[0] != "benchmark" and "total" not in r[0]}
        tracks.append([t.get(key, 0) for _, key in LAB])
    tot = [sum(t[i] for t in tracks) for i in range(len(LAB))]
    ymax = math.ceil(max(tot) * 1.10 / 2000) * 2000
    ticks = list(range(0, ymax + 1, 20000))
    plots = []
    for vals, fill, legend in zip(tracks, ("accent", "midnavy", "rulegrey"),
                                  ("primary track", "head-to-head track", "density sweep")):
        pts = " ".join(f"({lab},{v})" for (lab, _), v in zip(LAB, vals))
        plots.append(f"\\addplot[draw=brunelnavy,fill={fill}] coordinates\n  {{{pts}}};\n"
                     f"\\addlegendentry{{{legend}}}\n")
    nodes = "".join(f"\\node[font=\\scriptsize,color=textgrey,anchor=south] at "
                    f"(axis cs:{lab},{v}) {{{thousands(v)}}};\n" for (lab, _), v in zip(LAB, tot))
    return (header("Graded probes per benchmark and experimental track", "CORPUS_TRACKS.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=5.8cm,\n"
            f"  ybar stacked, bar width=17pt, ymin=0, ymax={ymax},\n"
            "  ylabel={graded trial answers},\n"
            "  symbolic x coords={" + ",".join(lab for lab, _ in LAB) + "},\n"
            "  xtick=data, ymajorgrids=true, axis x line*=bottom, axis y line*=left,\n"
            "  scaled y ticks=false, ytick={" + ",".join(str(t) for t in ticks) + "},\n"
            "  yticklabels={" + ",".join(thousands(t) if t < 1000 else "{" + thousands(t) + "}"
                                        for t in ticks) + "},\n"
            "  legend style={at={(0.98,0.97)},anchor=north east},legend cell align=left,\n"
            "  enlarge x limits=0.11]\n" + "".join(plots) + nodes +
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_overhead():
    from decimal import ROUND_HALF_UP, Decimal
    text = read("DISSERTATION_NUMBERS.md")
    ov = {r[0]: num(r[1]) for r in rows(text, "## Framework overhead") if "/" in r[0]}
    GROUPS = [("GPQA-D", ("gpqa_diamond",)), ("AIME", ("aime24", "aime25")),
              ("MMLU-Pro", ("mmlu_pro",)), ("MATH-500", ("math500",)), ("GSM8K", ("gsm8k",))]

    def vals(benches):
        return [v for k, v in ov.items() if k.split("/")[0] in benches and "Qwen3" in k]

    def r1(v):
        return Decimal(str(v)).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)
    deer = []
    for r in rows(read("DEER_OFFICIAL.md").split("\n## ")[0]):
        if r[0].startswith("Qwen3"):
            deer.append(100 * (float(r[4]) - float(r[3])) / float(r[3]))
    bars = " ".join(f"({np.mean(vals(b)):.2f},{lab})" for lab, b in GROUPS)
    nodes = "".join(f"\\node[font=\\scriptsize,color=textgrey,anchor=west] at "
                    f"(axis cs:88,{lab}){' ' * (9 - len(lab))}{{{r1(min(vals(b)))} to "
                    f"{r1(max(vals(b)))}\\%}};\n" for lab, b in GROUPS)
    mean = float(re.search(r"Mean over the (\d+) Qwen3 settings: ([\d.]+)%", text).group(2))
    n_set = int(re.search(r"Mean over the (\d+) Qwen3 settings", text).group(1))
    return (header("Probing overhead of the controller and of DEER",
                   "DISSERTATION_NUMBERS.md and DEER_OFFICIAL.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=5.4cm, width=11.6cm,\n"
            "  xbar, bar width=8pt,\n"
            "  xmin=0, xmax=108, xlabel={probing overhead (\\%)},\n"
            "  symbolic y coords={DEER,GSM8K,MATH-500,MMLU-Pro,AIME,GPQA-D},\n"
            "  ytick={DEER,GSM8K,MATH-500,MMLU-Pro,AIME,GPQA-D},\n"
            "  y tick label style={font=\\footnotesize}, xtick={0,20,40,60,80},\n"
            "  xmajorgrids=true, axis y line*=left, axis x line*=bottom,\n"
            "  enlarge y limits=0.16, clip=false]\n"
            f"\\addplot[draw=brunelnavy,fill=accent] coordinates\n  {{{bars}}};\n"
            f"\\addplot[draw=brunelnavy,fill=midnavy] coordinates {{({np.mean(deer):.1f},DEER)}};\n"
            + nodes +
            f"\\node[font=\\scriptsize,anchor=west] at (axis cs:88,DEER) "
            f"{{{round(min(deer))} to {round(max(deer))}\\%}};\n"
            "\\node[font=\\scriptsize\\itshape,color=accent,anchor=west]\n"
            f"  at (axis cs:12,MATH-500) {{controller: mean {mean:.1f}\\% over {words(n_set)} "
            "settings};\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_density():
    r = [row for row in rows(read("CKPT_DENSITY.md")) if row[0] == "Qwen3-4B" and "x " in row[1]]
    lev = ["1x", "2x", "4x"]
    acc = [(lv, num(row[6].split("@")[0])) for lv, row in zip(lev, r)]
    ovh = [(lv, num(row[4])) for lv, row in zip(lev, r)]
    return (header("Checkpoint density sweep (Qwen3-4B, MATH-500)", "CKPT_DENSITY.md") +
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[dissplot, height=5.4cm, width=11.6cm,\n"
            "  axis y line*=left, axis x line*=bottom,\n"
            "  xlabel={checkpoint density}, ylabel={NTC-Select accuracy, MATH-500},\n"
            "  symbolic x coords={1x,2x,4x}, xtick=data,\n"
            "  xticklabels={$1\\times$,$2\\times$,$4\\times$},\n"
            "  ymin=0.74, ymax=0.88, ymajorgrids=true,\n"
            "  legend style={at={(0.02,0.97)},anchor=north west}]\n"
            "\\addplot[draw=accent,line width=1.1pt,mark=*,mark size=2.2pt,\n"
            "         mark options={fill=accent}] coordinates {"
            + " ".join(f"({lv},{v:.3f})" for lv, v in acc) + "};\n"
            "\\addlegendentry{NTC-Select accuracy}\n"
            + "".join(f"\\node[font=\\scriptsize,color=textgrey,anchor=south] at "
                      f"(axis cs:{lv},{v:.3f}) {{{v:.3f}}};\n" for lv, v in acc) +
            "\\end{axis}\n"
            "\\begin{axis}[dissplot, height=5.4cm, width=11.6cm,\n"
            "  axis y line*=right, axis x line=none,\n"
            "  ylabel={probing overhead (\\% of full thinking)},\n"
            "  symbolic x coords={1x,2x,4x}, xtick=data,\n"
            "  ymin=0, ymax=14,\n"
            "  legend style={at={(0.98,0.20)},anchor=south east}]\n"
            "\\addplot[draw=brunelnavy,line width=1.1pt,dashed,mark=square*,mark size=2.0pt,\n"
            "         mark options={fill=brunelnavy}] coordinates {"
            + " ".join(f"({lv},{v:.1f})" for lv, v in ovh) + "};\n"
            "\\addlegendentry{probing overhead}\n"
            + "".join(f"\\node[font=\\scriptsize,color=textgrey,anchor=north] at "
                      f"(axis cs:{lv},{v:.1f}) {{{v:.1f}\\%}};\n" for lv, v in ovh) +
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_gate():
    dn = read("DISSERTATION_NUMBERS.md")
    gate = dn[dn.index("theta = 0.5:"):]
    g05 = rows(gate[:gate.index("theta = 0.9:")])
    g09 = rows(gate[gate.index("theta = 0.9:"):])
    GLAB = {"math500/Qwen3-4B": "MATH-4B", "gsm8k/Qwen3-8B": "GSM8K-8B",
            "gpqa_diamond/Qwen3-8B": "GPQA-8B", "mmlu_pro/Qwen3-4B": "MMLU-4B"}
    lo = [(GLAB[r[0]], num(r[2])) for r in g05 if r[0] in GLAB]
    hi = [(GLAB[r[0]], num(r[2])) for r in g09 if r[0] in GLAB]
    return (header("How often the confidence gate changes the halting decision",
                   "DISSERTATION_NUMBERS.md") +
            "\\begin{tikzpicture}\n\\begin{axis}[dissplot, height=5.2cm, width=12.4cm,\n"
            "  ybar, bar width=15pt, ymin=0, ymax=112,\n"
            "  ylabel={items whose halt the gate moves (\\%)},\n"
            "  symbolic x coords={" + ",".join(lab for lab, _ in lo) + "},\n"
            "  xtick=data, ymajorgrids=true, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.5,-0.19)},anchor=north,legend columns=2,column sep=1.1em},\n"
            "  nodes near coords={\\pgfmathprintnumber[fixed,precision=1]"
            "\\pgfplotspointmeta\\%},\n"
            "  nodes near coords style={font=\\scriptsize,color=textgrey},\n"
            "  enlarge x limits=0.18]\n"
            "\\addplot[draw=brunelnavy,fill=rulegrey] coordinates\n  {"
            + " ".join(f"({lab},{v})" for lab, v in lo) + "};\n"
            "\\addlegendentry{permissive gate, $\\theta = 0.5$}\n"
            "\\addplot[draw=brunelnavy,fill=accent] coordinates\n  {"
            + " ".join(f"({lab},{v})" for lab, v in hi) + "};\n"
            "\\addlegendentry{gate as calibrated, $\\theta = 0.9$}\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_h2h():
    h2h = [r for r in rows(read("H2H_TABLE.md")) if r[0].startswith("Qwen3")]
    HLAB = {"math500 (n=500)": "MATH-500", "gpqa_diamond (n=198)": "GPQA-D",
            "aime24 (n=30)": "AIME-24"}
    lines, labels = [], []
    pts = {"vanilla": [], "DEER": [], "AGREE": [], "NTC": []}
    for r in h2h:
        lab = f"{HLAB[r[1]]} {r[0].split('-')[1]}"
        labels.append(lab)
        v = [num(r[c].split("@")[0]) for c in (2, 3, 4, 5)]
        lines.append(f"\\draw[rulegrey,line width=1.1pt] (axis cs:{min(v)},{lab}) -- "
                     f"(axis cs:{max(v)},{lab});")
        for key, val in zip(["vanilla", "DEER", "AGREE", "NTC"], v):
            pts[key].append(f"({val},{lab})")
    MARK = {"vanilla": ("mark=o,draw=textgrey", "full generation"),
            "AGREE": ("mark=triangle*,draw=brunelnavy,fill=rulegrey", "answer agreement"),
            "NTC": ("mark=diamond*,draw=brunelnavy,fill=accent", "NTC selection tier"),
            "DEER": ("mark=square*,draw=brunelnavy,fill=brunelnavy", "DEER")}
    plots = "\n".join(
        f"\\addplot[only marks,{MARK[k][0]},mark size=2.6pt] coordinates {{{' '.join(pts[k])}}};\n"
        f"\\addlegendentry{{{MARK[k][1]}}}" for k in ["vanilla", "AGREE", "NTC", "DEER"])
    return (header("Matched comparison with DEER", "H2H_TABLE.md") +
            "\\begin{tikzpicture}\n\\begin{axis}[dissplot, height=6.0cm, width=12.0cm,\n"
            "  xlabel={accuracy on the same items}, xmin=0.18, xmax=1.0,\n"
            "  symbolic y coords={" + ",".join(reversed(labels)) + "},\n"
            "  ytick=data, y tick label style={font=\\scriptsize},\n"
            "  xmajorgrids=true, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.5,-0.22)},anchor=north,legend columns=4,column sep=0.8em},\n"
            "  enlarge y limits=0.12]\n" + "\n".join(lines) + "\n" + plots + "\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_fusiontransfer():
    f05 = {r[0].split(" (")[0]: r for r in rows(read("FUSION_TRANSFER.md"), "## eps = 0.05")}
    sh05 = {r[0].split(" (")[0]: r for r in rows(read("SHIFT_CERTIFICATE.md"), "## eps = 0.05")}
    BARS = [("tuned on one\\\\other domain", f05["transferred"]),
            ("fusion, safe on\\\\all others", f05["leave-one-domain-out"]),
            ("library, safe on\\\\all others", f05["library leave-one-domain-out, no bound"]),
            ("library, with\\\\Bonferroni bound", sh05["domain-robust"])]
    xcoords = ",".join(f"r{i}" for i in range(4))
    ticklabels = ",".join("{%s}" % b[0] for b in BARS)
    return (header("Which rule survives transfer",
                   "FUSION_TRANSFER.md and SHIFT_CERTIFICATE.md") +
            "\\begin{tikzpicture}\n\\begin{axis}[dissplot, height=5.6cm, width=12.8cm,\n"
            "  ybar, bar width=11pt, ymin=-26, ymax=112,\n"
            "  symbolic x coords={" + xcoords + "},\n"
            "  xtick=data, xticklabels={" + ticklabels + "},\n"
            "  x tick label style={font=\\scriptsize,align=center},\n"
            "  ymajorgrids=true, axis x line*=bottom, axis y line*=left,\n"
            "  legend style={at={(0.5,-0.30)},anchor=north,legend columns=3,column sep=0.9em},\n"
            "  enlarge x limits=0.14]\n"
            "\\addplot[draw=brunelnavy,fill=accent] coordinates {"
            + " ".join(f"(r{i},{num(b[1][4])})" for i, b in enumerate(BARS)) + "};\n"
            "\\addlegendentry{cells within $\\varepsilon$ (\\%)}\n"
            "\\addplot[draw=brunelnavy,fill=rulegrey] coordinates {"
            + " ".join(f"(r{i},{num(b[1][5])})" for i, b in enumerate(BARS)) + "};\n"
            "\\addlegendentry{mean token cut (\\%)}\n"
            "\\addplot[draw=brunelnavy,fill=midnavy] coordinates {"
            + " ".join(f"(r{i},{num(b[1][2])})" for i, b in enumerate(BARS)) + "};\n"
            "\\addlegendentry{worst cell (accuracy points)}\n"
            "\\draw[rulegrey,thin] (axis cs:r0,0) -- (axis cs:r3,0);\n"
            "\\end{axis}\n\\end{tikzpicture}\n")


def fig_kappa():
    tp = json.loads(read("TAIL_PRICE.json"))
    S, D = tp["settings"], tp["data"]

    def U(m, kap, worst=False):
        v = [D[m][s][1] - kap * max(0.0, -D[m][s][0]) for s in S]
        return min(v) if worst else sum(v) / len(v)

    CURVES = [("NTC-v2", "fusion tier", "accent", "solid"),
              ("NTC-full(e=0.05)", "selection tier", "midnavy", "dashed"),
              ("AGREE", "answer agreement", "brunelnavy", "dotted"),
              ("EAT", "entropy (EAT)", "textgrey", "densely dashdotted")]
    KAP = [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 25, 30]

    def panel(worst, title, ymin, ymax):
        body = []
        for key, lab, col, style in CURVES:
            p = " ".join(f"({k},{U(key, k, worst):.2f})" for k in KAP)
            body.append(f"\\addplot[draw={col},{style},line width=1.0pt] coordinates {{{p}}};\n"
                        f"\\addlegendentry{{{lab}}}")
        return ("\\begin{axis}[dissplot, height=5.4cm, width=6.6cm,\n"
                f"  title={{{title}}}, title style={{font=\\footnotesize\\itshape}},\n"
                "  xlabel={price of an accuracy point, $\\kappa$},\n"
                "  ylabel={utility (token-saving points)},\n"
                f"  xmin=0, xmax=30, ymin={ymin}, ymax={ymax}, grid=both,\n"
                "  axis x line*=bottom, axis y line*=left,\n"
                "  legend style={at={(0.03,0.03)},anchor=south west,font=\\scriptsize,\n"
                "                fill=white,fill opacity=0.85,text opacity=1,draw=rulegrey},\n"
                "  legend cell align=left]\n" + "\n".join(body) + "\n\\end{axis}")

    n = words(len(S))
    return (header("Utility against the price of an accuracy point", "TAIL_PRICE.json") +
            "\\begin{tikzpicture}\n" + panel(False, f"mean over the {n} settings", -60, 60) +
            "\n\\begin{scope}[xshift=7.4cm]\n" + panel(True, f"worst of the {n} settings", -160, 60) +
            "\n\\end{scope}\n\\end{tikzpicture}\n")


FIGURES = [fig_corpus, fig_heatmap, fig_collapse, fig_mechanism, fig_tradeoff, fig_shift,
           fig_slo, fig_overhead, fig_gate, fig_density, fig_h2h, fig_fusiontransfer, fig_kappa]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(ROOT / "figures" / "src"))
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    for f in FIGURES:
        (out / f"{f.__name__}.tex").write_text(f())
    print(f"wrote {len(FIGURES)} figures to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
