#!/usr/bin/env python
"""Paired tests, probing overhead, gate diagnostic and DeepSeek significance.

Four quantities reported in the dissertation that no other script writes:

  1. Paired tests against the fusion tier on operational-region AUCC
     (b in {0.4, 0.5, 0.6}), with the exact sign test and the tie-corrected
     Wilcoxon statistic of ntc_primary_stats.py (which tests against the
     selection tier instead).
  2. Probing overhead: the probe tokens paid by a controller that probes at every
     checkpoint and never halts, as a share of full-generation tokens (KV-fork
     convention of ntc_cost_regimes.py).
  3. The fusion tier's confidence-gate diagnostic at theta = 0.5 and 0.9, on four
     fixed probe files (ntc_v2_diagnostic.py).
  4. First-split significance on the DeepSeek setting: exact McNemar tests and a
     paired bootstrap of the token saving (ntc_w1_stats.py).

Inputs are the primary-track probe files. Writes
experiments/ntc/DISSERTATION_NUMBERS.md.

    python scripts/ntc_dissertation_numbers.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

import ntc_primary_stats as PS
import ntc_w1_stats as S
from ntc_v2_diagnostic import gate_rows

HERE = Path(__file__).resolve().parent
NTC = HERE.parent / "experiments" / "ntc"
REF = "NTC-v2 (fusion)"
SPLITS = 5
GATE_FILES = ["w1_math500_Qwen3-4B.json", "w1_gsm8k_Qwen3-8B.json",
              "w1sh_gpqa_Qwen3-8B.json", "w1_mmlupro_Qwen3-4B_s42.json"]


def probe_files() -> list[Path]:
    """The primary track: every w1_* and w1sh_* probe file."""
    return sorted(list(NTC.glob("w1_*.json")) + list(NTC.glob("w1sh_*.json")))


def op_aucc_per_setting() -> dict:
    groups = defaultdict(list)
    for pf in probe_files():
        d = json.loads(pf.read_text())
        groups[PS.setting_key(pf, d)].append(d)
    res = {}
    for key, ds in sorted(groups.items()):
        bench = ds[0]["benchmark"]
        reps = defaultdict(list)
        for d in ds:
            tr = d["traces"]
            for t in tr:
                t["natural_correct"] = bool(
                    S.is_correct(t.get("natural_answer", ""), t["gold"], bench))
            S.enrich_probes_with_nll(tr)
            for sd in range(SPLITS):
                _, op = PS.aucc_for_file(tr, bench, sd)
                for m, v in op.items():
                    reps[m].append(v)
        res[key] = {m: float(np.mean(v)) for m, v in reps.items()}
    return res


def overhead_per_setting() -> dict:
    groups = defaultdict(list)
    for pf in probe_files():
        d = json.loads(pf.read_text())
        groups[f"{d['benchmark']}/{d['model'].split('/')[-1]}"].append(d)
    res = {}
    for key, ds in sorted(groups.items()):
        tot, paid = [], []
        for d in ds:
            for t in d["traces"]:
                tot.append(t["n_total_tokens"])
                paid.append(t["n_total_tokens"] + sum(p["n_probe_tokens"] for p in t["probes"]))
        res[key] = float(np.mean(paid) / np.mean(tot) - 1.0)
    return res


def main() -> int:
    op = op_aucc_per_setting()
    md = ["# Paired tests, probing overhead, gate diagnostic and DeepSeek significance", "",
          "Generated by `scripts/ntc_dissertation_numbers.py` from the primary-track probe "
          f"files. Deployable protocol, {SPLITS} random calibration/evaluation splits per "
          "generation-seed file.", "",
          f"## Paired tests against the fusion tier ({REF}), operational-region AUCC", "",
          "| method | mean op-AUCC | s.d. | fusion wins | sign-test p | Wilcoxon z |",
          "|---|---|---|---|---|---|"]
    methods = sorted({m for v in op.values() for m in v},
                     key=lambda m: -np.mean([op[k][m] for k in op if m in op[k]]))
    for m in methods:
        vals = [op[k][m] for k in sorted(op) if m in op[k]]
        if m == REF:
            md.append(f"| {m} | {np.mean(vals):.3f} | {np.std(vals):.3f} | n/a | n/a | n/a |")
            continue
        d = [op[k][REF] - op[k][m] for k in sorted(op) if m in op[k]]
        p, pos, n = PS.sign_test(d)
        md.append(f"| {m} | {np.mean(vals):.3f} | {np.std(vals):.3f} | {pos}/{n} "
                  f"| {p:.4f} | {PS.wilcoxon_z(d):+.2f} |")
    md += ["", "## Per-setting operational-region AUCC", "",
           "| setting | " + " | ".join(methods) + " |",
           "|---|" + "---|" * len(methods)]
    for k in sorted(op):
        md.append(f"| {k} | " + " | ".join(f"{op[k].get(m, float('nan')):.3f}"
                                            for m in methods) + " |")

    ov = overhead_per_setting()
    qwen = [k for k in ov if "DeepSeek" not in k]
    md += ["", "## Framework overhead (probe at every checkpoint, never halt; KV-fork)", "",
           "| setting | overhead |", "|---|---|"]
    md += [f"| {k} | {100 * ov[k]:.2f}% |" for k in sorted(ov)]
    md += ["", f"Mean over the {len(qwen)} Qwen3 settings: "
               f"{100 * np.mean([ov[k] for k in qwen]):.2f}%.", ""]

    md += ["", "## Confidence-gate diagnostic (fusion m=3 versus agreement m=3)", "",
           "Files: " + ", ".join(f"`{f}`" for f in GATE_FILES) + ".", ""]
    for th in (0.5, 0.9):
        md += [f"theta = {th}:", "", "| setting | items | differs | delayed | identical? |",
               "|---|---|---|---|---|"] + gate_rows([NTC / f for f in GATE_FILES], 3, th) + [""]

    ds = NTC / "w1_math500_DeepSeek-R1-Distill-Qwen-7B.json"
    r = subprocess.run([sys.executable, str(HERE / "ntc_w1_stats.py"), "--probes", str(ds)],
                       check=True, capture_output=True, text=True)
    keep = [ln for ln in r.stdout.splitlines()
            if ln.startswith(("=== seed-0", "McNemar", "Bootstrap"))]
    md += ["## DeepSeek-R1-Distill-Qwen-7B on MATH-500: first-split significance", "",
           "```"] + keep + ["```", ""]
    out = NTC / "DISSERTATION_NUMBERS.md"
    out.write_text("\n".join(md))
    print("\n".join(md))
    print(f"\ntable: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
